##################### Naming Module ###################################################
#Reference the naming module and describe this application and environment
module "naming" {
  source                = "./naming"
  application_shortcode = "aaa"
  environment           = "production"
  location              = "UK South"
}

##################### Outputs ###################################################
#For this example, output some example resource names, generated by the naming module
output "resource_group_name" {
  value = module.naming.resource_name["resource_group"]
}

output "virtual_machine_name" {
  #In this example we are appending a suffix to the generated name.
  value = "${module.naming.resource_name["virtual_machine"]}-01"
}

output "storage_account_name" {
  value = module.naming.resource_name["storage_account"]
}

output "sql_server_name" {
  value = module.naming.resource_name["sql_server"]
}